### ISSUE TITLE
Broken links to source code

### ISSUE THREAD

**Issue by gabrielgt** [Acmion/CSharpWasmBenchmark#5]
Hi @Acmion! 

The links to source code on your 'production' page are broken:

For example: https://csharp-wasm-benchmark.acmion.com/CWasm/Benchmarks/ArraySortInt.c (KO) -> https://csharp-wasm-benchmark.acmion.com/Source/Implementations/CWasm/Benchmarks/ArraySortInt.c (OK)

By the way, thanks for the merge and the note in the credits 😉

**Comment by Acmion** [comment]
Thanks for the report! I fixed the URLs as well as the code that generates them.
